// swift-tools-version:5.7

// This file was automatically generated by PackageGenerator and untracked
// PLEASE DO NOT EDIT MANUALLY

import PackageDescription

let package = Package(
    name: "WFSUI",
    defaultLocalization: "en",
    platforms: [.iOS(.v13)],
    products: [
        .library(
            name: "WFSUI",
            type: .static,
            targets: ["WFSUI"]
        ),
    ],
    dependencies: [
    ],
    targets: [
        .target(
            name: "WFSUI",
            dependencies: [
            ],
            path: "WFSUI/Sources",
            resources: [
                .process("WFSUI/Resources")
            ],
            plugins: [
            ]
        ),
        .testTarget(
            name: "WFSUITests",
            dependencies: [
                .byName(name: "WFSUI"),
            ],
            path: "WFSUITests/Sources",
            plugins: [
            ]
        ),
    ],
    swiftLanguageVersions: [.v5]
)
